version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: workast:current-alpine
    env_file: .env
    container_name: app
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - AUTH_TOKEN=$AUTH_TOKEN
      - SLACK_TOKEN=$SLACK_TOKEN
    ports:
      - 8001:8001
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:4.4.2
    restart: unless-stopped
    env_file: .env
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - ./dbdata:/data/db
      - ./logs:/home/mongodb
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/$MONGO_DB --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s


